# This file was generated by GoReleaser. DO NOT EDIT.
class Ghbackup < Formula
  desc "Embarrassingly simple GitHub backup tool"
  homepage "https://qvl.io/ghbackup"
  version "1.13.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/qvl/ghbackup/releases/download/v1.13.0/ghbackup_1.13.0_mac_64bit.tar.gz"
    sha256 "f94bbcbbefba2d3c969e4530df35ccbe5cbfff7c582beb711f3840d3a4067316"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/qvl/ghbackup/releases/download/v1.13.0/ghbackup_1.13.0_linux_64bit.tar.gz"
      sha256 "838fd7ce830733db590708c4fb964bd28595dbb3878891141d23744180a7ac5d"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/qvl/ghbackup/releases/download/v1.13.0/ghbackup_1.13.0_linux_ARM64.tar.gz"
        sha256 "51ac603bb112d5fcbd9e6e2721ac841d151c79f2bf18259842c0424309d74382"
      else
        url "https://github.com/qvl/ghbackup/releases/download/v1.13.0/ghbackup_1.13.0_linux_ARM.tar.gz"
        sha256 "159695aafd6fe35f77c62abe630082a8de1a8439dc65b3ce164d4a92ce4b2cd9"
      end
    end
  end
  
  depends_on "git"

  def install
    bin.install "ghbackup"
  end
end
