# This file was generated by GoReleaser. DO NOT EDIT.
class Httpsyet < Formula
  desc "Find links you can update to HTTPS"
  homepage "https://qvl.io/httpsyet"
  version "0.2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/qvl/httpsyet/releases/download/v0.2.0/httpsyet_0.2.0_mac_64bit.tar.gz"
    sha256 "3c650e70fc5a0dcfebfdabfde208accd2497fed8e2a298b1976998a71854a33b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/qvl/httpsyet/releases/download/v0.2.0/httpsyet_0.2.0_linux_64bit.tar.gz"
      sha256 "cb75d8b3d75feb6f4d04a45b3134cd36df90a503be9479d991be295c08e108ec"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/qvl/httpsyet/releases/download/v0.2.0/httpsyet_0.2.0_linux_ARM64.tar.gz"
        sha256 "fd04517b3b3e10ac104ae394d45c242d7974bc047a4c54cce982a029270783c3"
      else
        url "https://github.com/qvl/httpsyet/releases/download/v0.2.0/httpsyet_0.2.0_linux_ARM.tar.gz"
        sha256 "2eefdf303bdf76155c18b39757b6749fd51dfefa1903e314dc4c91873e7f0bcf"
      end
    end
  end

  def install
    bin.install "httpsyet"
  end
end
