# This file was generated by GoReleaser. DO NOT EDIT.
class Promplot < Formula
  desc "Create plots from Prometheus metrics and send them to you"
  homepage "https://qvl.io/promplot"
  version "0.17.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/qvl/promplot/releases/download/v0.17.0/promplot_0.17.0_mac_64bit.tar.gz"
    sha256 "26dde35b17558b77bd50c59c592c5f958947aae2f1aac1cd437810113da07d69"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/qvl/promplot/releases/download/v0.17.0/promplot_0.17.0_linux_64bit.tar.gz"
    sha256 "8d02f99ce2ec83c78813fd63744b9f3628704a61f2eeb7bd4caa6f439e7ad904"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/qvl/promplot/releases/download/v0.17.0/promplot_0.17.0_linux_ARM.tar.gz"
    sha256 "b589fbd1e8911f0e23f516547dc2bbdc013a96f10f1272e5c47f1b937a91afbb"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/qvl/promplot/releases/download/v0.17.0/promplot_0.17.0_linux_ARM64.tar.gz"
    sha256 "4f0fc176e37c50fcd478195adf6f5274ae01a3af149c95438f71ffc603e8e81b"
  end

  def install
    bin.install "promplot"
  end
end
